### ISSUE TITLE
实习任务(打包维护)-字体包移植

### ISSUE THREAD

**Issue by Zeno-sole** [deepin-community/sig-deepin-sysdev-team#4]
任务需求： 移植其他开源社区的字体包到deepin v23中
完成标准：  通过CI/CD检查，代码合入仓库
字体包来源： 
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/sig-deepin-sysdev-team/issues/42
- [ ] https://github.com/deepin-community/sig-deepin-sysdev-team/issues/44
- [ ] https://github.com/deepin-community/sig-deepin-sysdev-team/issues/43
- [ ] google-noto https://fonts.google.com/noto https://github.com/deepin-community/sig-deepin-sysdev-team/issues/85
- [ ] https://github.com/deepin-community/sig-deepin-sysdev-team/issues/46
```
