### ISSUE TITLE
add nexttrace

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#497]
Add package `nexttrace`
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/golang-github-gorilla-websocket/pull/1
- [ ] https://github.com/deepin-community/golang-github-akamensky-argparse/pull/1
- [ ] https://github.com/deepin-community/golang-github-pelletier-go-buffruneio/pull/1
- [ ] https://github.com/deepin-community/golang-github-oschwald-maxminddb-golang/pull/1
- [ ] https://github.com/deepin-community/golang-gocapability/pull/1
- [ ] https://github.com/deepin-community/golang-github-tidwall-pretty/pull/1
- [ ] https://github.com/deepin-community/golang-github-tidwall-match/pull/1
- [ ] https://github.com/deepin-community/golang-github-mattn-go-runewidth/pull/1
- [ ] https://github.com/deepin-community/golang-github-rivo-uniseg/pull/1
- [ ] https://github.com/deepin-community/gopacket/pull/1
- [ ] https://github.com/deepin-community/golang-github-tidwall-gjson/pull/1
- [ ] https://github.com/deepin-community/golang-github-rodaine-table/pull/1
- [ ] https://github.com/deepin-community/golang-github-lionsoul2014-ip2region-v1.0-binding-golang-ip2region/pull/1
- [ ] https://github.com/deepin-community/nexttrace/pull/1
- [ ] https://github.com/deepin-community/golang-gocapability/pull/2
- [ ] https://github.com/deepin-community/nexttrace/pull/2
- [ ] https://github.com/linuxdeepin/developer-center/issues/5216
```

**Comment by YukariChiba** [comment]
Done.
