### ISSUE TITLE
add pipewire / wireplumber and replace pulseaudio

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#498]
https://github.com/orgs/linuxdeepin/discussions/3898
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/wireplumber/pull/1
- [ ] https://github.com/deepin-community/pipewire/pull/1
- [ ] https://github.com/deepin-community/liblc3/pull/1
- [ ] https://github.com/deepin-community/libfreeaptx/pull/1
- [ ] https://github.com/deepin-community/libcamera/pull/1
- [ ] https://github.com/deepin-community/deepin-desktop-environment/pull/20
- [ ] https://github.com/deepin-community/xfonts-encodings/pull/2
- [ ] https://github.com/linuxdeepin/dde-daemon/pull/530
- [ ] https://github.com/deepin-community/liblc3/pull/2
- [ ] https://github.com/deepin-community/libfreeaptx/pull/2
- [ ] https://github.com/deepin-community/libcamera/pull/2
- [ ] https://github.com/linuxdeepin/developer-center/issues/5016
- [ ] https://github.com/linuxdeepin/developer-center/issues/5017
- [ ] https://github.com/deepin-community/wireplumber/pull/2
- [ ] https://github.com/deepin-community/deepin-desktop-environment/pull/22
- [ ] https://github.com/linuxdeepin/developer-center/issues/5193
- [ ] https://github.com/linuxdeepin/dde-daemon/pull/540
- [ ] https://github.com/linuxdeepin/dde-session/pull/34
- [ ] https://github.com/linuxdeepin/developer-center/issues/5222
- [ ] https://github.com/linuxdeepin/developer-center/issues/5231
- [ ] https://github.com/linuxdeepin/developer-center/issues/5240
```
