### ISSUE TITLE
实习任务(打包维护)-流行软件包移植

### ISSUE THREAD

**Issue by Zeno-sole** [deepin-community/sig-deepin-sysdev-team#5]
任务需求： 移植具有一定流行度的软件包到deepin 23中
完成标准： 通过CI/CD检查，PR合入仓库
任务补充： 参照软件包统计表移植deepin 23中没有的软件包到https://github.com/deepin-community  尽量选取排名靠前的软件包
软件包统计表:  https://popcon.debian.org/by_inst
相比与debian仓库deepin仓库中缺少的软件包:  https://ci.deepin.com/repo/deepin/deepin-ports/deb/pkg-list.txt
ps: 提交上来的软件务必在本地验证构建

**Comment by Zeno-sole** [comment]
补充rust相关依赖包，可能会存在相互依赖问题，可以使用topic解决(参见wiki 搜索相关词条)

- [x] librust-memchr-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/10
- [x] librust-aho-corasick-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/11
- [x] librust-aho-corasick+std-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/15
- [x] librust-winapi-i686-pc-windows-gnu-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/36
- [x] librust-winapi-x86-64-pc-windows-gnu-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/37
- [x] librust-winapi-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/35
- [x] librust-ansi-term-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/67
- [x] librust-libc-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/17
- [ ] librust-atty-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/38
- [ ] librust-bitflags-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/13
- [x] librust-version-check-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/57
- [x] librust-nom-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/19
- [x] librust-nom+std-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/27
- [x] librust-cexpr-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/75
- [x] librust-cfg-if-0.1-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/21
- [x] librust-glob-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/59
- [x] librust-clang-sys-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/90
- [ ] librust-unicode-width-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/99
- [ ] librust-textwrap-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/98
- [x] librust-clap-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/76
- [ ] librust-clap+color-dev
- [x] librust-strsim-dev  https://github.com/deepin-community/sig-deepin-sysdev-team/issues/56
- [ ] librust-clap+strsim-dev
- [x] librust-vec-map-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/63
- [ ] librust-clap+default-dev
- [x] librust-cloudabi-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/80
- [ ] librust-cloudabi+default-dev
- [ ] librust-log-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/22
- [ ] librust-env-logger-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/303
- [ ] librust-humantime-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/32
- [ ] librust-regex-syntax-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/101
- [ ] librust-regex-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/108
- [ ] librust-scopeguard-dev 
- [ ] librust-lock-api-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/484
- [ ] librust-redox-syscall-dev
- [ ] librust-smallvec-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/221
- [ ] librust-parking-lot-core-dev
- [x] librust-parking-lot-dev
- [ ] librust-once-cell-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/145
- [ ] librust-thread-local-dev
- [ ] librust-regex+perf-cache-dev
- [ ] librust-regex+perf-literal-dev
- [ ] librust-regex+perf-dev
- [x] librust-winapi-util-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/28
- [x] librust-termcolor-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/82
- [ ] librust-env-logger+default-dev
- [x] librust-lazy-static-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/60
- [x] librust-lazycell-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/77
- [x] librust-peeking-take-while-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/96
- [x] librust-unicode-xid-dev
- [x] librust-unicode-ident-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/34
- [x] librust-proc-macro2-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/33
- [x] librust-quote-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/25
- [ ] librust-regex+unicode-age-dev
- [ ] librust-regex+unicode-bool-dev
- [ ] librust-regex+unicode-case-dev
- [ ] librust-regex+unicode-perl-dev
- [ ] librust-regex+unicode-gencat-dev
- [ ] librust-regex+unicode-script-dev
- [ ] librust-regex+unicode-segment-dev
- [ ] librust-regex-syntax+unicode-dev
- [ ] librust-regex+unicode-dev
- [x] librust-rustc-hash-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/48
- [x] librust-shlex-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/29
- [x] librust-which-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/26
- [x] apt-rdepends https://github.com/deepin-community/sig-deepin-sysdev-team/issues/16
- [x] wipe https://github.com/deepin-community/sig-deepin-sysdev-team/issues/20
- [x] rephrase  https://github.com/deepin-community/sig-deepin-sysdev-team/issues/31
- [x] realmd https://github.com/deepin-community/sig-deepin-sysdev-team/issues/61
- [x] parole https://github.com/deepin-community/sig-deepin-sysdev-team/issues/54 
- [x] librust-either-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/64
- [ ] discus https://github.com/deepin-community/sig-deepin-sysdev-team/issues/62
- [ ] librust-lexical-core-0.4+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/81
- [x] librust-clap-lex https://github.com/deepin-community/sig-deepin-sysdev-team/issues/83
- [x] librust-os-str-bytes-6+raw-os-str-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/84
- [x] librust-ryu-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/92
- [ ] librust-stackvector-1-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/93
- [ ] librust-unicode-linebreak+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/107
- [x] librust-smawk+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/105
- [ ] librust-hashbrown+default-dev  https://github.com/deepin-community/sig-deepin-sysdev-team/issues/109
- [x] librust-dtoa-0.4+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/131
- [x] librust-libm-0.2+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/132
- [ ] librust-rustc-version-0.4+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/133
- [x] librust-semver-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/134
- [ ] librust-unreachable-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/135
- [x] librust-void-1-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/136
- [x] librust-static-assertions-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/137
- [ ] librust-criterion-0.3+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/139
- [x] librust-fnv-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/140
- [ ] librust-fxhash-0.2+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/141
- [ ] librust-getrandom-0.2+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/142
- [ ] librust-hex-0.4+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/143
- [ ] librust-no-panic-0.1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/144
- [ ] librust-rand-0.8+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/146
- [ ] librust-seahash-4+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/147
- [ ] librust-serde-json-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/148
- [ ] librust-byteorder-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/244
- [ ] libicu-73 https://github.com/deepin-community/sig-deepin-sysdev-team/issues/260
- [ ] librust-autocfg-1+default-dev https://github.com/deepin-community/sig-deepin-sysdev-team/issues/485

**Comment by UTsweetyfish** [comment]
rust 语言相关的软件包，在 debian 是由 rust-team 维护的。通过 [debcargo](https://salsa.debian.org/rust-team/debcargo) 和 [debcargo-conf](https://salsa.debian.org/rust-team/debcargo-conf) 进行维护。

ref: https://wiki.debian.org/Teams/RustPackaging

一个一个包在 github 维护感觉是很不方便、很不合适的。

**Comment by Zeno-sole** [comment]
> rust 语言相关的软件包，在 debian 是由 rust-team 维护的。通过 [debcargo](https://salsa.debian.org/rust-team/debcargo) 和 [debcargo-conf](https://salsa.debian.org/rust-team/debcargo-conf) 进行维护。
> 
> ref: https://wiki.debian.org/Teams/RustPackaging
> 
> 一个一个包在 github 维护感觉是很不方便、很不合适的。

是的，你可以想一下怎么在deepin-community 和obs上去跑这个流程
