### ISSUE TITLE
misc tasks by @YukariChiba

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#500]
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/btop/pull/1
- [ ] https://github.com/deepin-community/mmdebstrap/pull/1
- [ ] https://github.com/vioken/qwlroots/pull/171
- [ ] https://github.com/deepin-community/gnu-which/pull/1
- [ ] https://github.com/deepin-community/fakechroot/pull/1
- [ ] https://github.com/deepin-community/pacman-package-manager/pull/1
- [ ] https://github.com/deepin-community/fonts-android/pull/2
```

```[tasklist]
### Integrates
- [ ] https://github.com/linuxdeepin/developer-center/issues/5011
- [ ] https://github.com/linuxdeepin/developer-center/issues/5141
```

```[tasklist]
### Package Management
- [ ] https://github.com/deepin-community/Repository-Manager/pull/224
- [ ] https://github.com/deepin-community/Repository-Manager/pull/245
- [ ] https://github.com/deepin-community/Repository-Manager/pull/255
- [ ] https://github.com/deepin-community/Repository-Manager/pull/260
- [ ] https://github.com/deepin-community/Repository-Manager/pull/266
- [ ] https://github.com/deepin-community/Repository-Manager/pull/291
- [ ] https://github.com/deepin-community/Repository-Manager/pull/292
- [ ] https://github.com/deepin-community/Repository-Manager/pull/308
- [ ] https://github.com/deepin-community/Repository-Manager/pull/317
```
