### ISSUE TITLE
topic: deprecation of typed_ast

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#515]
Src: https://github.com/python/typed_ast/issues/179
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/Repository-Manager/pull/254
- [ ] https://github.com/deepin-community/black/pull/1
- [ ] https://github.com/deepin-community/typeshed/pull/1
- [ ] https://github.com/deepin-community/python-typing-extensions/pull/1
- [ ] https://github.com/deepin-community/python-mypy-extensions/pull/1
- [ ] https://github.com/deepin-community/mypy/pull/3
```
