### ISSUE TITLE
Upgrade and fix python

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#516]
- remove python 3.9
- switch default to python 3.11
- upgrade python 3.11
- build python packages based on python 3.10, 3.11

```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/python3.11/pull/1
- [ ] https://github.com/deepin-community/python3-defaults/pull/1
- [ ] https://github.com/deepin-community/setuptools-scm/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/255
- [ ] https://github.com/deepin-community/Repository-Manager/pull/261
- [ ] https://github.com/deepin-community/Repository-Manager/pull/262
- [ ] https://github.com/deepin-community/Repository-Manager/pull/268
```

```[tasklist]
### Topic
- [ ] https://github.com/deepin-community/flit/pull/2
- [ ] https://github.com/deepin-community/wheel/pull/1
- [ ] https://github.com/deepin-community/ufolib2/pull/1
- [ ] https://github.com/deepin-community/tox/pull/1
- [ ] https://github.com/deepin-community/setuptools-scm/pull/2
- [ ] https://github.com/deepin-community/setuptools/pull/2
- [ ] https://github.com/deepin-community/python3-stdlib-extensions/pull/1
- [ ] https://github.com/deepin-community/python-tomli-w/pull/2
- [ ] https://github.com/deepin-community/python-pytest-benchmark/pull/1
- [ ] https://github.com/deepin-community/python-pyproj/pull/1
- [ ] https://github.com/deepin-community/python-pathspec/pull/1
- [ ] https://github.com/deepin-community/python-pip/pull/4
- [ ] https://github.com/deepin-community/python-msgpack/pull/1
- [ ] https://github.com/deepin-community/python-hypothesis/pull/1
- [ ] https://github.com/deepin-community/python-fs/pull/1
- [ ] https://github.com/deepin-community/python-attrs/pull/1
- [ ] https://github.com/deepin-community/python-flake8/pull/1
- [ ] https://github.com/deepin-community/python-argcomplete/pull/1
- [ ] https://github.com/deepin-community/pyflakes/pull/2
- [ ] https://github.com/deepin-community/pycodestyle/pull/1
- [ ] https://github.com/deepin-community/proj/pull/1
- [ ] https://github.com/deepin-community/platformdirs/pull/1
- [ ] https://github.com/deepin-community/lxml/pull/1
- [ ] https://github.com/deepin-community/furo/pull/1
- [ ] https://github.com/deepin-community/trove-classifiers/pull/1
- [ ] https://github.com/deepin-community/testresources/pull/1
- [ ] https://github.com/deepin-community/hatchling/pull/1
- [ ] https://github.com/deepin-community/hatch-vcs/pull/1
- [ ] https://github.com/deepin-community/markdown-it-py/pull/1
- [ ] https://github.com/deepin-community/mdit-py-plugins/pull/1
- [ ] https://github.com/deepin-community/mdurl/pull/1
- [ ] https://github.com/deepin-community/myst-parser/pull/1
- [ ] https://github.com/deepin-community/poetry-core/pull/1
- [ ] https://github.com/deepin-community/python-click-default-group/pull/1
- [ ] https://github.com/deepin-community/python-cattrs/pull/1
- [ ] https://github.com/deepin-community/python-exceptiongroup/pull/1
- [ ] https://github.com/deepin-community/python-hatch-fancy-pypi-readme/pull/1
- [ ] https://github.com/deepin-community/python-tomlkit/pull/1
- [ ] https://github.com/deepin-community/python-unicodedata2/pull/1
- [ ] https://github.com/deepin-community/sphinx-basic-ng/pull/1
- [ ] https://github.com/deepin-community/sphinx-notfound-page/pull/1
- [ ] https://github.com/deepin-community/sphinx-reredirects/pull/1
- [ ] https://github.com/deepin-community/towncrier/pull/1
- [ ] https://github.com/deepin-community/python-mock/pull/1
- [ ] https://github.com/deepin-community/flit-scm/pull/1
- [ ] https://github.com/deepin-community/fonttools/pull/1
```
