### ISSUE TITLE
add qemu >= 7.2

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#517]
- `libbpf1`
- `libfdt1 (>= 1.6.1)` -> `device-tree-compiler`
- `libgmp10 (>= 2:6.2.1+dfsg1)` -> `gmp`
- `libgnutls30 (>= 3.7.5)` -> `gnutls28`
- `libibverbs1` -> `rdma-core`
- `libpmem1`
- `librdmacm1` -> `rdma-core`
- `libsasl2-2 (>= 2.1.28+dfsg)`
- `libslirp0 (>= 4.7.0)`
- `liburing2 (>= 2.3)`
- `libvdeplug2`
- `seabios`
- `ipxe-qemu`
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/libbpf/pull/1
- [ ] https://github.com/deepin-community/device-tree-compiler/pull/1
- [ ] https://github.com/deepin-community/gmp/pull/1
- [ ] https://github.com/deepin-community/gnutls28/pull/1
- [ ] https://github.com/deepin-community/rdma-core/pull/1
```

- `brltty>=6.4`
- `spice (>=0.14.2)`
- `ipxe-qemu`

```[tasklist]
### QEMU 7.1 deps
7. [ ] https://github.com/deepin-community/brltty/pull/1
7. [ ] https://github.com/deepin-community/spice/pull/1
7. [ ] https://github.com/deepin-community/Repository-Manager/pull/327
```
