### ISSUE TITLE
add cataclysm-dda

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#522]
操作系统仓库里要有一款**开放世界游戏**
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/opusfile/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/288
- [ ] https://github.com/deepin-community/fonts-homecomputer/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/289
- [ ] https://github.com/deepin-community/vfit/pull/1
- [ ] https://github.com/deepin-community/qmltermwidget/pull/1
- [ ] https://github.com/deepin-community/3270font/pull/1
- [ ] https://github.com/deepin-community/cool-retro-term/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/290
- [ ] https://github.com/deepin-community/fonts-pc/pull/1
- [ ] https://github.com/deepin-community/fonts-atarismall/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/295
- [ ] https://github.com/deepin-community/cataclysm-dda/pull/1
- [ ] https://github.com/linuxdeepin/developer-center/issues/5378
- [ ] https://github.com/deepin-community/architecture-properties/pull/1
- [ ] https://github.com/linuxdeepin/developer-center/issues/5400
```
