### ISSUE TITLE
postgresql-14 test error / upgrade

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#523]
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/Repository-Manager/pull/309
- [ ] https://github.com/deepin-community/postgresql-15/pull/1
- [ ] https://github.com/deepin-community/Repository-Manager/pull/321
- [ ] https://github.com/deepin-community/Repository-Integration/pull/463
- [ ] https://github.com/deepin-community/postgresql-common/pull/1
- [ ] https://github.com/linuxdeepin/developer-center/issues/5527
```
