### ISSUE TITLE
add openttd

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#525]
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/Repository-Manager/pull/298
- [ ] https://github.com/deepin-community/Repository-Manager/pull/303
- [ ] https://github.com/deepin-community/Repository-Manager/pull/304
- [ ] https://github.com/deepin-community/Repository-Manager/pull/306
- [ ] https://github.com/deepin-community/Repository-Manager/pull/307
- [ ] https://github.com/deepin-community/libmypaint/pull/1
- [ ] https://github.com/deepin-community/nml/pull/1
- [ ] https://github.com/deepin-community/openttd-openmsx/pull/1
- [ ] https://github.com/deepin-community/catcodec/pull/1
- [ ] https://github.com/deepin-community/openttd-opensfx/pull/1
- [ ] https://github.com/deepin-community/openttd-opengfx/pull/1
- [ ] https://github.com/deepin-community/grfcodec/pull/2
- [ ] https://github.com/deepin-community/openttd/pull/1
- [ ] https://github.com/linuxdeepin/developer-center/issues/5387
```
