### ISSUE TITLE
add prismlauncher

### ISSUE THREAD

**Issue by YukariChiba** [deepin-community/sig-deepin-sysdev-team#526]
```[tasklist]
### Tasks
- [ ] https://github.com/deepin-community/Repository-Manager/pull/291
- [ ] https://github.com/deepin-community/Repository-Manager/pull/305
- [ ] https://github.com/deepin-community/nlohmann-json3/pull/1
- [ ] https://github.com/deepin-community/tomlplusplus/pull/1
- [ ] https://github.com/deepin-community/libquazip1-qt6/pull/1
- [ ] https://github.com/deepin-community/prismlauncher/pull/1
- [ ] https://github.com/deepin-community/Repository-Integration/pull/411
```
