### ISSUE TITLE
qt 6.6 transition

### ISSUE THREAD

**Issue by UTsweetyfish** [deepin-community/sig-deepin-sysdev-team#539]
https://github.com/orgs/deepin-community/projects/41
https://build.deepin.com/project/show/deepin:CI:topics:qt6

### TODO

```[tasklist]
- [ ] **qt6-grpc** **NEW REPO**
- [ ] **qt6-lottie**
- [ ] **qt6-scxml**
- [ ] qt6-3d
- [ ] qt6-charts
- [ ] qt6-datavis3d
- [ ] qt6-httpserver
- [ ] qt6-multimedia
- [ ] qt6-networkauth
- [ ] qt6-quick3d
- [ ] qt6-quick3dphysics
- [ ] qt6-remoteobjects
- [ ] qt6-sensors
- [ ] qt6-speech
- [ ] qt6-virtualkeyboard
- [ ] qt6-webengine
- [ ] qt6-webview
```

#### 第一批 

https://github.com/linuxdeepin/developer-center/issues/6228

```[tasklist]
- [x] qt6-base
- [x] qt6-declarative
- [x] qt6-languageserver
- [x] qt6-shadertools
- [x] qt6-svg
- [x] qt6-tools
- [x] qt6-wayland
```

#### 第二批

https://github.com/linuxdeepin/developer-center/issues/6265

```[tasklist]
- [x] qt6-5compat
- [x] qt6-imageformats
- [x] qt6-serialbus
- [x] qt6-serialport
- [x] Rebuild fcitx5-qt
- [x] qt6-connectivity https://github.com/deepin-community/qt6-connectivity/pull/4
- [x] qt6-positioning https://github.com/deepin-community/qt6-positioning/pull/4
- [x] qt6-quicktimeline https://github.com/deepin-community/qt6-quicktimeline/pull/3
- [x] qt6-translations https://github.com/deepin-community/qt6-translations/pull/3
- [x] qt6-webchannel https://github.com/deepin-community/qt6-webchannel/pull/3
- [x] qt6-websockets https://github.com/deepin-community/qt6-websockets/pull/5
```
