### ISSUE TITLE
Packages in multi-section

### ISSUE THREAD

**Issue by UTsweetyfish** [deepin-community/sig-deepin-sysdev-team#553]
```[tasklist]
### Tasks
- [ ] broadcom-sta: 6.30.223.271-24 main, community
- [ ] deepin-unstable-source: 0.0.6-2 main, community
- [ ] dh-builtusing: 0.0.6 main, community
- [ ] fonts-nanum: 20200506-1 main, community
- [ ] galera-3: 25.3.34-1 main, community
- [ ] golang-github-containernetworking-plugins: 1.1.1+ds1-3 main, community
- [ ] grub-customizer: 5.2.3-1 main, community
- [ ] haskell-uniplate: 1.6.13-1 main, community
- [ ] hfst-ospell: 0.5.3-2 main, community
- [ ] highway: 1.0.7-8 main, community
- [ ] libhtml-scrubber-perl: 0.19-2 main, community
- [ ] libjs-requirejs-text: 2.0.12-1.1 main, community
- [ ] libperl-minimumversion-perl: 1.40-1 main, community
- [ ] libquazip: 0.9.1-3deepin1 main, community
- [ ] libtest-tcp-perl: 2.22-2 main, community
- [ ] libtpms: 0.9.2-3.1 main, community
- [ ] libwww-form-urlencoded-perl: 0.26-2 main, community
- [ ] libwww-form-urlencoded-xs-perl: 0.28-1 main, community
- [ ] node-sinclair-typebox: 0.24.44-3 main, community
- [ ] nvtop: 3.0.2-1 main, community
- [ ] opensbi: 1.3.1-1 main, community
- [ ] pyte: 0.8.0-2 main, community
- [ ] ruby-minitar: 0.9-1 main, community
- [ ] ruby-sdbm: 1.0.0-5 main, community
- [ ] seafile: 9.0.3-1 main, community
- [ ] template-repository: 1.0-1 main, community
- [ ] xdg-terminal-exec: 0~20230318-1 main, community
```

```[tasklist]
### Tasks
- [ ] bird2: main (`2.15.1-1`), community (`2.13.1-1`)
- [ ] containerd: main (`1.6.24~ds1-1deepin1`), community (`1.6.18~ds1-1`)
- [ ] dbus-c++: main (`0.9.0-12`), community (`0.9.0-10`)
- [ ] docker.io: main (`20.10.25+dfsg1-2deepin1`), community (`20.10.23+dfsg1-1`)
- [ ] fastfetch: main (`2.8.10-0deepin`), community (`2.4.0-0deepin`)
- [ ] filezilla: main (`3.66.4-2`), community (`3.65.0-3`)
- [ ] firefox: main (`126.0.1-1deepin1`), community (`127.0-1deepin1`)
- [ ] fonts-smiley-sans: main (`2.1.0-0deepin`), community (`1.1.1-0deepin`)
- [ ] fonts-tuffy: main (`20120614-3`), community (`20120614-2.1`)
- [ ] gimp: main (`2.10.36-3`), community (`2.10.38-1deepin1`)
- [ ] glmark2: main (`2023.01+dfsg-1`), community (`2023.01+dfsg-1deepin1`)
- [ ] golang-github-mdlayher-netlink: main (`1.7.1-1deepin1`), community (`1.6.0`)
- [ ] golang-github-mdlayher-socket: main (`0.5.1-1deepin1`), community (`0.2.1`)
- [ ] ieee-data: main (`20220827.1`), community (`20210605.1`)
- [ ] iputils: main (`3:20210202-1`), community (`3:20240117-1`)
- [ ] libfilezilla: main (`0.45.0-5`), community (`0.44.0-3`)
- [ ] libgd-barcode-perl: main (`2.00-1`), community (`1.15-7`)
- [ ] liblol: main (`0.1.4-1`), community (`0.1.5-1`)
- [ ] librime: main (`1.10.0+dfsg1-1`), community (`1.11.2+dfsg1-1deepin1`)
- [ ] nlohmann-json3: main (`3.11.3-1`), community (`3.11.2-2deepin1`)
- [ ] node-http-proxy: main (`1.18.1-8deepin1`), community (`1.18.1-8`)
- [ ] node-nock: main (`13.3.3-1deepin1`), community (`13.3.3-1`)
- [ ] node-propagate: main (`2.0.1-4deepin1`), community (`2.0.1-4`)
- [ ] odc: main (`1.5.0-2`), community (`1.4.6-5`)
- [ ] open-vm-tools: main (`2:12.4.0-1deepin1`), community (`2:12.2.0-1`)
- [ ] osc: main (`0.169.1-2deepin1`), community (`0.169.1-2`)
- [ ] partclone: main (`0.3.18.1-deepin`), community (`0.3.27+repack-1`)
- [ ] r-base: main (`4.3.1-4+rb1`), community (`4.3.1-4`)
- [ ] ruby-mini-portile2: main (`2.8.5-1`), community (`2.8.4-1`)
- [ ] runc: main (`1.1.10+ds1-1deepin1`), community (`1.1.4+ds1-1`)
- [ ] schroot: main (`1.6.13-3+rb1`), community (`1.6.13-3`)
- [ ] thefuck: main (`3.29-0.3`), community (`3.32-0.1`)
- [ ] wireshark: main (`4.2.0-1`), community (`4.2.6-1deepin1`)
- [ ] nvidia-graphics-drivers: community (`530.41.03-3deepin2`), commercial (`535.161.08-2`)
```

```[tasklist]
### Tasks
- [ ] rust-aho-corasick: 0.7.19-1 main, community
- [ ] rust-ansi-term: 0.12.1-1 main, community
- [ ] rust-atty: 0.2.14-2 main, community
- [ ] rust-bytemuck: 1.12.1-1 main, community
- [ ] rust-byteorder: 1.4.3-2 main, community
- [ ] rust-cexpr: 0.6.0-2 main, community
- [ ] rust-clang-sys: 1.3.0-1 main, community
- [ ] rust-compiler-builtins: 0.1.70-1 main, community
- [ ] rust-device-tree: 1.1.0-1 main, community
- [ ] rust-erased-serde: 0.3.23-1 main, community
- [ ] rust-fnv: 1.0.7-1 main, community
- [ ] rust-fxhash: 0.2.1-1 main, community
- [ ] rust-getrandom: 0.2.8-1 main, community
- [ ] rust-hex: 0.4.3-1 main, community
- [ ] rust-humantime: 2.1.0-1 main, community
- [ ] rust-itoa: 1.0.1-2 main, community
- [ ] rust-lazycell: 1.3.0-3 main, community
- [ ] rust-libm: 0.2.1-5 main, community
- [ ] rust-memchr: 2.5.0-1 main, community
- [ ] rust-minimal-lexical: 0.2.1-2 main, community
- [ ] rust-no-panic: 0.1.13-1 main, community
- [ ] rust-os-str-bytes: 6.0.0-1 main, community
- [ ] rust-peeking-take-while: 0.1.2-1 main, community
- [ ] rust-ppv-lite86: 0.2.16-1 main, community
- [ ] rust-rustc-hash: 1.1.0-1 main, community
- [ ] rust-rustc-std-workspace-core: 1.0.0-1 main, community
- [ ] rust-rustc-version: 0.4.0-1 main, community
- [ ] rust-ryu: 1.0.2-1 main, community
- [ ] rust-same-file: 1.0.6-1 main, community
- [ ] rust-seahash: 4.1.0-1 main, community
- [ ] rust-shlex: 1.1.0-1 main, community
- [ ] rust-smawk: 0.3.1-2 main, community
- [ ] rust-static-assertions: 1.1.0-1 main, community
- [ ] rust-strsim: 0.10.0-1 main, community
- [ ] rust-syn-1: 1.0.109-2 main, community
- [ ] rust-termcolor: 1.1.2-1 main, community
- [ ] rust-unicode-ident: 1.0.0-1 main, community
- [ ] rust-unicode-width: 0.1.10-1 main, community
- [ ] rust-unreachable: 1.0.0-1 main, community
- [ ] rust-version-check: 0.9.4-1 main, community
- [ ] rust-void: 1.0.2-1 main, community
- [ ] rust-which: 4.2.5-1 main, community
- [ ] rust-winapi: 0.3.9-1 main, community
- [ ] rust-winapi-i686-pc-windows-gnu: 0.4.0-1 main, community
- [ ] rust-winapi-util: 0.1.5-1 main, community
- [ ] rust-winapi-x86-64-pc-windows-gnu: 0.4.0-1 main, community
```

```[tasklist]
### Tasks
- [ ] rust-arbitrary: main (`1.3.0-1`), community (`1.1.3-1`)
- [ ] rust-bitflags: main (`2.4.0-1`), community (`2.3.2-1`)
- [ ] rust-cfg-if: main (`1.0.0-1`), community (`1.0.0-2`)
- [ ] rust-clap: main (`4.1.13-2`), community (`4.0.32-1`)
- [ ] rust-clap-lex: main (`0.5.0-1`), community (`0.3.0-1`)
- [ ] rust-derive-arbitrary: main (`1.3.1-1`), community (`1.1.3-1`)
- [ ] rust-dtoa: main (`1.0.9-1`), community (`0.4.3-1`)
- [ ] rust-either: main (`1.9.0-1`), community (`1.6.1-1`)
- [ ] rust-glob: main (`0.3.1-1`), community (`0.3.0-1`)
- [ ] rust-lazy-static: main (`1.4.0-2`), community (`1.4.0-1`)
- [ ] rust-libc: main (`0.2.150-1`), community (`0.2.146-1`)
- [ ] rust-log: main (`0.4.20-2`), community (`0.4.17-4`)
- [ ] rust-nom: main (`7.1.3-1`), community (`7.1.1-1`)
- [ ] rust-once-cell: main (`1.18.0-1`), community (`1.17.0-1`)
- [ ] rust-proc-macro2: main (`1.0.86-1`), community (`1.0.60-1`)
- [ ] rust-quote: main (`1.0.30-1`), community (`1.0.21-1`)
- [ ] rust-rand-core: main (`0.6.4-1`), community (`0.6.3-2`)
- [ ] rust-regex: main (`1.7.3-1`), community (`1.7.1-1`)
- [ ] rust-regex-syntax: main (`0.6.29-1`), community (`0.6.27-1`)
- [ ] rust-scopeguard: main (`1.1.0-1`), community (`1.1.0-2`)
- [ ] rust-semver: main (`1.0.18-1`), community (`1.0.14-1`)
- [ ] rust-serde: main (`1.0.171-1`), community (`1.0.152-2`)
- [ ] rust-serde-json: main (`1.0.103-1`), community (`1.0.87-1`)
- [ ] rust-smallvec: main (`1.11.0-1`), community (`1.9.0-1`)
- [ ] rust-sval: main (`2.6.1-2`), community (`1.0.0~alpha.5-3`)
- [ ] rust-walkdir: main (`2.4.0-1`), community (`2.3.2-1`)
```

**Comment by UTsweetyfish** [comment]
- main+community 版本相同: [same.txt](https://github.com/user-attachments/files/16705796/same.txt)
- 版本不同: [different.json](https://github.com/user-attachments/files/16705863/different.json)

**Comment by UTsweetyfish** [comment]
nvidia-graphics-drivers:
- community (`530.41.03-3deepin2`)
- commercial (`535.161.08-2`)

**Comment by UTsweetyfish** [comment]
Done by @Zeno-sole.
